### PR TITLE
xbox: Fix support for CCI launching on supported kernel

### PR DESCRIPTION
**Pull request by GXTX**
Very displeased with the lack of support from the community that was so strongly pushing for global CCI support.

Would recommend squashing this when merged.

### CODE REVIEW

**Comment by LoveMHz** [comment]
Can we wrap this around a kernel check as it appears to target a specific BIOS in a non-agnostic manner?

This is important for future kernels that may support this file format or others.

**Comment by GXTX** [comment]
> Can we wrap this around a kernel check as it appears to target a specific BIOS in a non-agnostic manner?
> 
> This is important for future kernels that may support this file format or others.

Agreed. Added. :)

**Comment by LoveMHz** [comment]
Request for time to review before merging.

**Comment by GXTX** [comment]
Status?

**Comment by Ryzee119** [comment]
Busy with work. Maybe in the next week or so

**Comment by Ryzee119** [comment]
Thanks for this too

**Pull request merged**
